### ISSUE TITLE
repo URL in delorean.repo file on http://buildlogs.centos.org/centos/7/cloud/x86_64/rdo-trunk-master/

### ISSUE THREAD

**Issue by sshnaidm** [openstack-packages/DLRN#26]
After discussion with @javierpena I open the issue about URL of repo in http://buildlogs.centos.org/centos/7/cloud/x86_64/rdo-trunk-master/delorean.repo that points to http://trunk.rdoproject.org instead of  http://buildlogs.centos.org/

**Comment by javierpena** [comment]
To understand the issue, let's try to follow the chain of events:

- DLRN builds a package, then creates a repo on a hashed dir (using the commit and distgit hashes). The delorean.repo file is created, using the hashed dir as baseurl. If the repo is consistent, DLRN will create a consystent symlink to that hashed dir.

- There are several CI jobs that test this repo, and some of them may create a symlink under trunk.rdoproject.org/centos7-master, pointing to the hashed dir:
  - tripleo-ci
  - current-passed-ci
  - maybe others?

- Since the same hashed dir can be promoted by different pipelines, we cannot simply make delorean.repo point to http://buildlogs.centos.org/ . All CIs would be pointing to the most current consistent repo, instead of their specific ones. Even worse, if we have commit A, B and C, and all are consistent, but we just want to test commit A, we'd have the same repo file for all of them.

**Comment by javierpena** [comment]
So now that the problem is stated, I'll try to propose a solution:

- For any CI job that needs to use the "consistent" repo, do not download delorean.repo. Instead, create a repo file by hand pointing to http://buildlogs.centos.org/centos/7/cloud/x86_64/rdo-trunk-master/ . You can use the delorean.repo file if the specific hash needs to be stored somewhere.

- For CI promotion jobs, We can make each job create its own tripleo-ci.repo | current-passed-ci.repo file, also pointing to the buildlogs URL. That way, any CI job that needs to use them (such as gate jobs) can take advantage of the CDN, and we keep the delorean.repo file around to know what hash it is using.

**Comment by sshnaidm** [comment]
We use consistent in periodic promotion jobs only.
Actually I had a patch that creates a new repo file in CI scripts, but because now things run fast and I don't see any problem with the speed I think we can close this issue. I'll keep eye on it and will reopen it in case this problem appears again.

Thanks, @javierpena
